using System.Collections.Generic;

namespace DungeonCrawlerWorld.Utilities
{
    /// <summary>
    /// Represents formatted display text with metadata.
    /// This object is meant to be generated by the StringUtility and consumed by the UserInterface.
    /// </summary>
    public class DisplayText
    {
        public List<string> FormattedTextLines { get; set; }

        /// <value>When true, indicates that at least one line of the formatted text has been truncated.</value>
        public bool IsTruncated { get; set; }

        /// <value>The original unformatted text. Readonly.</value>
        public string OriginalText { get; }

        public DisplayText(string originalText)
        {
            OriginalText = originalText;
            FormattedTextLines = new List<string>();
            IsTruncated = false;
        }
    }
    
}