namespace DungeonCrawlerWorld.Utilities
{
    /// <summary>
    /// Represents formatted display text with metadata.
    /// This object is meant to be generated by the StringUtility and consumed by the UserInterface.
    /// </summary>
    public readonly struct DisplayText(string originalText, string formattedText, int lineCount)
    {
        public string FormattedText { get; } = formattedText.TrimEnd('\r', '\n');

        /// <value>The original unformatted text. Readonly.</value>
        public string OriginalText { get; } = originalText;

        /// <value>The number of text lines to be displayed based on inserted newlines.</value>
        public int LineCount { get; } = lineCount;
    }
}